# dev.yml is a configuration for setting up development environments for Shopify toolchains.
# You may be able to use this tool outside of shopify with Minidev
# See: https://github.com/burke/minidev, but you're probably better off installing ruby manually and using bundle installing
# like any other ruby project.
name: product-taxonomy

type: ruby

up:
  - ruby: 3.3.0
  - bundler
