name: Taxonomy Tree Requests
description: File a request to change the Taxonomy Tree
title: "[Taxonomy Tree]: "
labels:
  - "taxonomy-tree-request"
body:
  - type: dropdown
    id: taxonomy_field
    attributes:
      label: Taxonomy Field
      multiple: false
      options:
        - Category
        - Attribute
        - Value
  - type: dropdown
    id: vertical
    attributes:
      label: Vertical
      multiple: false
      options:
        - Animals & Pet Supplies
        - Apparel & Accessories
        - Arts & Entertainment
        - Baby & Toddler
        - Business & Industrial
        - Cameras & Optics
        - Electronics
        - Food, Beverages & Tobacco
        - Furniture
        - Hardware
        - Health & Beauty
        - Home & Garden
        - Luggage & Bags
        - Mature
        - Media
        - Office Supplies
        - Religious & Ceremonial
        - Services
        - Software
        - Sporting Goods
        - Toys & Games
        - Vehicles & Parts
        - Product Add-ons
  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      multiple: false
      options:
        - New category or attribute
        - Rename category or attribute
        - Assign attribute to more categories
        - Remove attribute from category
        - New attribute value
        - Rename attribute value
        - Assign value to more attributes
        - Remove attribute value
        - Other
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: "Provide a brief summary of your issue. For example: 'Missing category for Sombrero Hats.'"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe your experience in more detail. For example: 'I didn't find a suitable category or fitting attributes for my product, even though we have one for Baseball Caps.'"
    validations:
      required: true
  - type: textarea
    id: video_screenshot
    attributes:
      label: Video/Screenshot
      description: Attach any relevant videos or screenshots to this text area.
    validations:
      required: false
  - type: input
    id: merchant_store
    attributes:
      label: Merchant Store
      description: If you'd like us to review your store or another merchant's store, please link it here.
    validations:
      required: false
