name: Run Minitest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0

    - name: Install dependencies
      working-directory: ./dev
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run tests
      working-directory: ./dev
      run: bin/rake test

    - name: Set up Cue
      uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'

    - name: Verify generation output
      working-directory: ./dev
      run: |
        bin/generate_dist
        bin/verify_dist_files
