name: Generate and commit all distribution files

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "full_dist"
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_SHA_SHORT: $(git rev-parse --short ${{ github.sha }})

jobs:
  generate_full_dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Cue
      uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'

    - name: Install bundler and gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Generate distribution files
      run: make VERBOSE=1 LOCALES=all

    - name: Commit changes and create PR
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "🤖 Update localization files for ${{ github.sha }}"
        branch: create-pull-request/localization
        branch-suffix: short-commit-hash
        title: "🤖 Update localization files for ${GITHUB_SHA_SHORT}"
        body: Update `dist/` localization files. Triggered by ${GITHUB_SHA_SHORT}.
        labels: automated-pr, localization
