name: Generate and commit all distribution files

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

concurrency:
  group: "dist"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  generate_dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Cue
      uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'

    - name: Install bundler and gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Generate distribution files
      run: make LOCALES=all

    - name: Get last commit author
      id: last_author
      run: |
        author=$(git log -1 --pretty=format:'%an')
        echo "::set-output name=author::$author"

    - name: Commit distribution files
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        branch_name="dist-update-branch-${GITHUB_RUN_ID}"
        git checkout -b $branch_name
        git add dist
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update distribution files" || exit 0 # Exit gracefully if no changes
          git push origin $branch_name
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.branch_name }}
        title: "🤖 Update distribution files"
        body: "This PR updates the distribution files. @${{ steps.last_author.outputs.author }}, please review and merge."
        labels: automated-pr
        reviewers: "@${{ steps.last_author.outputs.author }}"
