name: Generate and commit all distribution files

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "full_dist"
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_full_dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Cue
      uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'

    - name: Install bundler and gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Generate distribution files
      run: make VERBOSE=1 LOCALES=all

    - name: Get last commit author
      id: last_author
      run: |
        author=$(git log -1 --pretty=format:'%an')
        echo "::set-output name=author::$author"

    - name: Commit changes and create PR
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "🤖 Update localization files for ${{ github.sha }}"
        branch-suffix: short-commit-hash
        title: "🤖 Update localization files: ${{ github.ref }}"
        body: |
          Update distribution localization files. Triggered by ${{ github.sha }} from ${{ github.ref }}.

          @${{ steps.last_author.outputs.author }}, please review and merge.
        labels: automated-pr
        assignees: ${{ steps.last_author.outputs.author }}
        reviewers: ${{ steps.last_author.outputs.author }}
