name: Generate and commit all distribution files

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "full_dist"
  cancel-in-progress: false

permissions:
  contents: write

env:
  branch_name: "dist-update-branch-${GITHUB_RUN_ID}"

jobs:
  generate_full_dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Cue
      uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'

    - name: Install bundler and gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Generate distribution files
      run: make LOCALES=all

    - name: Get last commit author
      id: last_author
      run: |
        author=$(git log -1 --pretty=format:'%an')
        echo "::set-output name=author::$author"

    - name: Commit distribution files
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add dist
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          COMMIT_SHA=$(git rev-parse HEAD | cut -c1-7)

          git checkout -b ${{ env.branch_name }}
          git commit -m "🤖 Update localization files for $(COMMIT_SHA)" || exit 0 # Exit gracefully if no changes
          git push origin ${{ env.branch_name }}
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.branch_name }}
        title: "🤖 Update localization files"
        body: "This PR updates the distribution localization files. @${{ steps.last_author.outputs.author }}, please review and merge."
        labels: automated-pr
        reviewers: "@${{ steps.last_author.outputs.author }}"
