name: Generate and commit distribution files to requested PR

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

concurrency:
  group: "dist"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  generate_dist:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/generate_dist' }}
    steps:
    - uses: actions/checkout@v4
    - name: Checkout PR
      run: gh pr checkout $ISSUE
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'
    - name: Generate distribution files
      run: make VERBOSE=1
    - name: Commit distribution files
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add dist
        git commit -m "🤖 Update distribution files" || exit 0 # Exit gracefully if no changes
        git push
