name: Generate and commit distribution files for all locales

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

concurrency:
  group: "dist"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  generate_dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout PR
      run: gh pr checkout $ISSUE
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Cue
      uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'

    - name: Install bundler and gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Generate distribution files
      run: make LOCALES=all

    - name: Commit distribution files
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add dist
        git commit -m "🤖 Update distribution files" || exit 0 # Exit gracefully if no changes
        git push
